<?php
return [
  'lista' => [
    'ARGOS PREPARATORY ACADEMY S. C.',
    'BACHILLERARO TECNOLOGICO DE LA UNIVERSIDAD TRES CULTURAS',
    'Bachillerato Instituto Metepec',
    'Bachillerato ISES Bravo',
    'Bachillerato Tecnológico Villa de los Niños',
    'Bachillerato UNITECIB',
    'C.B.T TEMOAYA',
    'C.B.T. AMANALCO DE BECERRA',
    'C.B.T. C.P. NO. 5 ALBERTO MENA FLORES',
    'C.B.T. CALMECAC',
    'C.B.T. CAPULHUAC',
    'C.B.T. N°2 ALMOLYA DE JUAREZ',
    'C.B.T. n°3 tenango del valle, san francisco putla',
    'C.B.T. No 3 TENANGO DEL VALLE',
    'C.B.T. NO. 2 DR. MARIO JOSE MOLINA HENRIQUEZ, TOLUCA',
    'C.B.T. No.2 Almoloya de Juarez',
    'C.B.T. No.2 IXTAPAN DE LA SAL',
    'C.B.T. No.3 ALMOLOYA DE JUAREZ',
    'C.B.T. No.3 Toluca',
    'C.B.T. No.4 TOLUCA',
    'C.B.T. NO.5 " C.P. ALBERTO MENA FLORES", Toluca',
    'C.B.T. No.5 Alberto Mena Flores, Toluca',
    'C.B.T. Num. 2 Ixtapan De La Sal',
    'C.B.T. TEMOAYA',
    'C.B.T. Tenancingo',
    'C.B.T. VILLA VICTORIA',
    'Cardenal Posadas Ocampo',
    'CBTIS 203 GRL. IGNACION BETETA QUINTANA',
    'ceb 6/9 "jaime torres bodet"',
    'Opción 30',
    'CECYTEM PLANTEL DONATO GUERRA',
    'CECYTEM plantel ixtapan de la sal',
    'CECyTEM plantel metepec',
    'CECYTEM PLANTEL TENANCINGO',
    'CECYTEM plantel villa victoria',
    'CENTRO BACHILLERATO TECNOLOGICO No. 4',
    'Centro de bachillerato jose vasconcelos, S.C',
    'CENTRO DE BACHILLERATO TECNOLÓGICO AGROPECUARIO N°223',
    'Centro de Bachillerato Tecnológico Habitat',
    'CENTRO DE BACHILLERATO TECNOLOGICO INDUSTRIAL Y DE SERVICIO NO. 203',
    'CENTRO DE BACHILLERATO TECNOLOGICO INDUSTRIAL Y DE SERVICIOS NO.161',
    'CENTRO DE BACHILLERATO TECNOLOGICO INDUSTRIAL Y DE SERVICIOS No.56',
    'CENTRO DE BACHILLERATO TECNOLÓGICO No. 1 ALMOLOYA DE JUAREZ MEXTEPEC',
    'CENTRO DE BACHILLERATO TECNOLOGICO NO. 4 TOLUCA',
    'CENTRO DE BACHILLERATO TECNOLOGICO No.1 EMILIANO ZAPATA',
    'CENTRO DE BACHILLERATO TECNOLOGICO Ocuilan',
    'CENTRO DE BACHILLERATO TECNOLOGICO TENANCINGO',
    'CENTRO DE BACHILLERATO TECNOLOGICO-Calmécac-',
    'Centro de Bachillerato Tecnológico-Chimalpopoca-',
    'Centro de Bachillerato Tecnológico-Cuauhtinchan-',
    'Centro de Bachillerato Tecnológico-Dr. Ezequiel Capistrán Rodríguez-',
    'Centro de Bachillerato Tecnológico-Gabriel V. Alcocer-',
    'Centro de Bachillerato Tecnológico-Huemac Santo Tomas de los Plátanos-',
    'Centro de Bachillerato Tecnológico-Ignacio López Rayón-',
    'Centro de Bachillerato Tecnológico-Ing. Esteban Calderón Alcaraz-',
    'Centro de Bachillerato Tecnológico-Justo Sierra-',
    'Centro de Bachillerato Tecnológico-Lic. Adolfo López Mateos-',
    'Centro de Bachillerato Tecnológico-Lic. Mario Colín Sánchez-',
    'Centro de Bachillerato Tecnológico-Prof. Guillermo Menez Servín-',
    'Centro de Bachillerato Tecnológico-Prof. Luis Camarena González-',
    'CENTRO DE EDUCACIÓN MEDIA SUPERIOR DE LA UNIVERSIDAD AUTÓNOMA DE AGUASCALIENTES',
    'CENTRO DE ESTUDIOS DE BACHILLERATO 6/9 "JAIME TORRES BODETH"',
    'Centro de Estudios de Bachillerato Taxco',
    'Centro de Estudios de Bachillerato-Lic. Jesús Reyes Heroles-',
    'Centro de Estudios de Bachillerato-Victoriano Agüeros-',
    'centro de estudios jesus reyes heroles',
    'centro de estudios puebla',
    'Centro de Estudios Superiores Olimpo',
    'CENTRO DE ESTUDIOS SUPERIORES UNIVERSITARIOS "CESU"',
    'Centro de Estudios Técnicos en Administración, Computación y secretariales',
    'CENTRO DE ESTUDIOS TECNOLÓGICO INDUSTRIAL Y DE SERVICIOS No. 23',
    'CENTRO DE ESTUDIOS TECNOLÓGICO INDUSTRIAL Y DE SERVICIOS NO. 64',
    'Centro de Estudios Tecnológicos del Estado de México',
    'Centro de Estudios Universitarios Horacio Zúñiga',
    'CENTRO DE ESTUDIOS UNIVERSITARIOS INDEPENDECIA',
    'CENTRO DE FORMACIÓN EDUCATIVOS DE TEMOAYA',
    'Centro de Sistemas Computacionales',
    'Centro Educativo Cruz Azul, A.C.-Plantel Hidalgo-',
    'CENTRO EDUCATIVO CUAUTITLAN IZCALLI',
    'Centro Educativo y Tecnológico Tollocan, S.C.',
    'CENTRO UNIVERSITARIO LICEO MEXIQUENSE, S.C.',
    'Centro Universitario Siglo XXI, S.C.',
    'Centros de Estudios Superiores Atenea Palas, S.C.',
    'CETIS 64',
    'COBAEM Colegio de Bachilleres del Estado de México 60 TEMOAYA',
    'COBAEM Colegio de Bachilleres del Estado de México PLANTEL 006 Toluca Norte',
    'COBAEM Colegio de Bachilleres del Estado de México PLANTEL 07 TOLUCA SUR',
    'COBAEM Colegio de Bachilleres del Estado de México PLANTEL 24',
    'COBAEM Colegio de Bachilleres del Estado de México PLANTEL 32 TOLUCA 3',
    'COBAEM Colegio de Bachilleres del Estado de México PLANTEL 41 TEMASCALCINGO',
    'COBAEM Colegio de Bachilleres del Estado de México PLANTEL TOLUCA II',
    'COBAEM Colegio de Bachilleres del Estado de México PLANTEL TOLUCA SUR 2',
    'COBAEM Colegio de Bachilleres del Estado de México PLANTEL ZINACANTEPEZ 01',
    'Colegio Alma Mater',
    'Colegio Antonio Plancarte, A.C.',
    'Colegio Baden Powell',
    'Colegio de Bachilleres del Estado de Guerrero',
    'Colegio de Bachilleres del Estado de Hidalgo-Plantel Francisco I. Madero-',
    'COLEGIO DE BACHILLERES DEL ESTADO DE MEXICO PLANTEL 38 ACAMBAY',
    'Colegio de Bachilleres del Estado de Michoacán-Plantel Tuxpan-',
    'Colegio de Bachilleres del Estado de Puebla',
    'Colegio de Bachilleres-Aeropuerto-',
    'colegio de estudios cientifico y tecnologico del Estado de Oaxaca',
    'Colegio de Estudios Científicos y Tecnológicos del Estado de Durango-Lerdo-',
    'COLEGIO DE ESTUDIOS CIENTÍFICOS Y TECNOLÓGICOS DEL ESTADO DE MEXICO',
    'COLEGIO DE ESTUDIOS CIENTÍFICOS Y TECNOLÓGICOS DEL ESTADO DE MÉXICO PLANTEL HUIXQUILUCAN',
    'COLEGIO DE ESTUDIOS CIENTIFICOS Y TECNOLOGICOS DEL ESTADO DE MEXICO PLANTEL METEPEC 1',
    'COLEGIO DE ESTUDIOS CIENTIFICOS Y TECNOLOGICOS DEL ESTADO DE MEXICO PLANTEL METEPEC II',
    'COLEGIO DE ESTUDIOS CIENTÍFICOS Y TECNOLÓGICOS DEL ESTADO DE MÉXICO PLANTEL METEPEC l',
    'COLEGIO DE ESTUDIOS CIENTÍFICOS Y TECNOLÓGICOS DEL ESTADO DE MÉXICO PLANTEL TOLUCA',
    'COLEGIO DE ESTUDIOS CIENTÍFICOS Y TECNOLÓGICOS DEL ESTADO DE MÉXICO PLANTEL VILLA DE ALLENDE',
    'Colegio de Estudios Científicos y Tecnológicos del Estado de México-Coacalco-',
    'Colegio de Estudios Científicos y Tecnológicos del Estado de México-Coatepec Harinas-',
    'Colegio de Estudios Científicos y Tecnológicos del Estado de México-Ixtlahuaca-',
    'Colegio de Estudios Científicos y Tecnológicos del Estado de México-Malinalco-',
    'Colegio de Estudios Científicos y Tecnológicos del Estado de México-Metepec-',
    'Colegio de Estudios Científicos y Tecnológicos del Estado de México-Metepec-',
    'Colegio de Estudios Científicos y Tecnológicos del Estado de México-Plantel Núm 1, Metepec-',
    'Colegio de Estudios Científicos y Tecnológicos del Estado de México-San Antonio Buenavista-',
    'Colegio de Estudios Científicos y Tecnológicos del Estado de México-San Felipe del Progreso-',
    'Colegio de Estudios Científicos y Tecnológicos del Estado de México-San Pedro del Rincón-',
    'Colegio de Estudios Científicos y Tecnológicos del Estado de México-Santa Ana Ixtlahuatzingo-',
    'Colegio de Estudios Científicos y Tecnológicos del Estado de México-Santa Cruz Tepexpan-',
    'Colegio de Estudios Científicos y Tecnológicos del Estado de México- Temascaltepec-',
    'Colegio de Estudios Científicos y Tecnológicos del Estado de México-Tenango del Valle-',
    'Colegio de Estudios Científicos y Tecnológicos del Estado de México-Villa Victoria-',
    'Colegio de Estudios Científicos y Tecnológicos del Estado de México-Xonacatlan-',
    'COLEGIO GAUDI',
    'Colegio las Américas, S.C.',
    'Colegio Latinoamericano Siglo XXI',
    'Colegio Mexiquense de Bachillerato',
    'Colegio Mexiquense de Educación Tecnológica',
    'Colegio Motolinia',
    'Colegio Nacional de Educacion Profesional Tecnica',
    'Colegio Nacional de Educacion Profesional Técnica Santiago Tianguistenco',
    'COLEGIO NACIONAL DE MATEMATICAS',
    'Colegio Preparatorio',
    'Colegio provincial de educación secundaria no.21 Jose Font',
    'Colegio Springfield, S.C.',
    'CONALEP aeropuerto',
    'CONALEP No.008 EL ORO, MEX.',
    'CONAMAT',
    'EMEDYVA, S.C.',
    'Escuela de Estudios Profesionales de Atlixco',
    'Escuela Preparatoria del Centro Universitario de Ixtlahuaca Químico José Donaciano',
    'ESCUELA PREPARATORIA DEL CENTRO UNIVERSITARIO DE IXTLAHUACA QUIMICO JOSE DONACIANO MORALES',
    'ESCUELA PREPARATORIA OFICIAL ANEXA A LA CENTENARIA Y BENEMERITA ESCUELA NORMAL PARA PROFESORES',
    'ESCUELA PREPARATORIA OFICIAL ANEXA A LA NORMAL DE ATLACOMULCO',
    'Escuela Preparatoria Oficial Anexa a la Normal de Atlacomulco',
    'Escuela Preparatoria Oficial Anexa a la Normal de Capulhuac',
    'Escuela Preparatoria Oficial Anexa a la Normal de Coatepec Harinas',
    'Escuela Preparatoria Oficial Anexa a la Normal de Ixtapan de la Sal',
    'Escuela Preparatoria Oficial Anexa a la Normal de IXTLAHUACA',
    'Escuela Preparatoria Oficial Anexa a la Normal de Jilotepec',
    'Escuela Preparatoria Oficial Anexa a la Normal de Naucalpan',
    'Escuela Preparatoria Oficial Anexa a la Normal de San Felipe del Progreso',
    'Escuela Preparatoria Oficial Anexa a la Normal de Santa Ana Zicatecoyan',
    'Escuela Preparatoria Oficial Anexa a la Normal de SANTIAGO TIANGUISTENCO',
    'Escuela Preparatoria Oficial Anexa a la Normal de SantiagoTianquistenco',
    'Escuela Preparatoria Oficial Anexa a la Normal de Sultepec',
    'Escuela Preparatoria Oficial Anexa a la Normal de Tejupilco',
    'Escuela Preparatoria Oficial Anexa a la Normal de Tenancingo',
    'Escuela Preparatoria Oficial Anexa a la Normal de Valle de Bravo',
    'Escuela Preparatoria Oficial Anexa a la Normal No. 1 de Toluca',
    'Escuela Preparatoria Oficial Anexa a la Normal NO.3 DE TOLUCA',
    'Escuela Preparatoria Oficial Anexa a la Normal para Profesores',
    'ESCUELA PREPARATORIA OFICIAL NO. 1 ANEXA A LA ENSEM',
    'ESCUELA PREPARATORIA OFICIAL NUM. 002',
    'ESCUELA PREPARATORIA OFICIAL NUM. 008',
    'ESCUELA PREPARATORIA OFICIAL NUM. 033',
    'ESCUELA PREPARATORIA OFICIAL NUM. 044',
    'ESCUELA PREPARATORIA OFICIAL NUM. 045',
    'ESCUELA PREPARATORIA OFICIAL NUM. 056',
    'ESCUELA PREPARATORIA OFICIAL NUM. 090',
    'ESCUELA PREPARATORIA OFICIAL NUM. 093',
    'ESCUELA PREPARATORIA OFICIAL NUM. 149',
    'ESCUELA PREPARATORIA OFICIAL NUM. 151',
    'ESCUELA PREPARATORIA OFICIAL NUM. 165',
    'ESCUELA PREPARATORIA OFICIAL NUM. 169',
    'ESCUELA PREPARATORIA OFICIAL NUM. 180',
    'ESCUELA PREPARATORIA OFICIAL NUM. 182',
    'ESCUELA PREPARATORIA OFICIAL NUM. 192',
    'ESCUELA PREPARATORIA OFICIAL NUM. 193, SAN DIEGO CUENTLA, SAN SIMÓN DE GUERRERO',
    'ESCUELA PREPARATORIA OFICIAL NUM. 196',
    'ESCUELA PREPARATORIA OFICIAL NUM. 197',
    'ESCUELA PREPARATORIA OFICIAL NUM. 199',
    'ESCUELA PREPARATORIA OFICIAL NUM. 201',
    'ESCUELA PREPARATORIA OFICIAL NUM. 209',
    'ESCUELA PREPARATORIA OFICIAL NUM. 215 jorge obispo hernadez',
    'ESCUELA PREPARATORIA OFICIAL NUM. 230',
    'ESCUELA PREPARATORIA OFICIAL NUM. 239',
    'ESCUELA PREPARATORIA OFICIAL NUM. 244 EL SEMINARIO',
    'ESCUELA PREPARATORIA OFICIAL NUM. 245',
    'ESCUELA PREPARATORIA OFICIAL NUM. 249 de Villa Victoria',
    'ESCUELA PREPARATORIA OFICIAL NUM. 261',
    'ESCUELA PREPARATORIA OFICIAL NUM. 273',
    'ESCUELA PREPARATORIA OFICIAL NUM. 287',
    'ESCUELA PREPARATORIA OFICIAL NUM. 291, TENANGO DEL VALLE',
    'ESCUELA PREPARATORIA OFICIAL NUM. 292',
    'ESCUELA PREPARATORIA OFICIAL NUM. 297',
    'ESCUELA PREPARATORIA OFICIAL NUM. 302',
    'ESCUELA PREPARATORIA OFICIAL NUM. 305',
    'ESCUELA PREPARATORIA OFICIAL NUM. 319',
    'Escuela Preparatoria Regional-Aculco Venustiano Carranza',
    'Escuela Preparatoria Regional-Amatepec-',
    'Escuela Preparatoria Regional-Capulhuac Josué Mirlo-',
    'Escuela Preparatoria Regional-Huixquilucan-',
    'Escuela Preparatoria Regional-Santiago Tianguistenco-',
    'Escuela Preparatoria Regional-Santiago Tilapa-',
    'Escuela Preparatoria Regional-Tejupilco-',
    'Escuela Preparatoria Regional-Temascaltepec-',
    'Escuela Preparatoria Regional-Villa del Carbón-',
    'Escuela Preparatoria Regional-Villa Victoria-',
    'Escuela Preparatoria, UAS-Concordia-',
    'EXTRANJERO',
    'GRUPO ISIMA TOLUCA',
    'HUNAB',
    'INSTITUTO AL SERVICIO EDUCATIVO SUPERIOR',
    'Instituto Brima, S.C.',
    'Instituto CENCA, S.C.',
    'Instituto Cultural Cumbres del Saber, S.C.',
    'Instituto Cultural EFIHME, S.C.',
    'Instituto Cultural Paideia, S.C.',
    'Instituto de Ciencias de la Comunicación',
    'Instituto de Educación Media Superior del Distrito Federal-Plantel Josefa Ortiz de Domínguez-',
    'Instituto de Estudios Técnicos ISIMA',
    'INSTITUTO EDUCATIVO ESPAÑA,S.C',
    'Instituto Galeana, S.C.',
    'Instituto ICEL',
    'Instituto Latino, S.C.',
    'Instituto Leonardo Bravo, A.C.-Plantel Centro-',
    'INSTITUTO METEPEC',
    'Instituto México de Toluca, A.C.',
    'Instituto Milenium, S.C.',
    'Instituto para la Educación Integral del Bachiller, S.C.',
    'Instituto Profesional en la Enseñanza y Formación Humana, S.C.',
    'INSTITUTO SECUNDARIA SUPROFESIONAL',
    'Instituto Secundaria y Educación Subprofesional, S.C.',
    'Instituto secundario de educacion superior',
    'Instituto Simón Bolívar',
    'Instituto Técnico Administrativo y Humanístico de Toluca, A.C.',
    'Instituto Tecnológico de Estudios Superiores de Monterrey - Campus Toluca, sede Metepec',
    'Instituto Tecnológico de Superación Integral',
    'Instituto Tecnológico y de Estudios Superiores de Monterrey-Campus Toluca-',
    'INSTITUTO TECNOLÓGICO Y UNIVERSITARIO DEL ESTADO DE MEXICO',
    'Instituto Terranova de Estudios Generales',
    'Instituto Universitario Auriga, A.C.',
    'INSTITUTO UNIVERSITARIO CUITLAHUAC A.C',
    'Instituto Universitario del Lago y del Sol',
    'Instituto Universitario Franco Ingles de México, S.C.',
    'Instituto Universitario y Tecnológico del Estado de México, S.C.',
    'INSTUTUTO TECNICO ADMINISTRATIVO Y HUMANISTICO DE TOLUCA',
    'intituto univercitario y tecnologico del estado de mexico',
    'ISES',
    'IUEM',
    'IUEM-Campus Atlacomulco',
    'Liceo del Valle de Toluca, S.C.',
    'Lighthouse Christian Academy',
    'Plantel "Atlacomulco" de la Escuela Preparatoria (Prepa Atlacomulco)',
    'Plantel "Cuauhtémoc" de la Escuela Preparatoria (Prepa 3)',
    'Plantel "Dr. Angel María Garibay" de la Escuela Preparatoria (Prepa 5)',
    'Plantel "Dr. Pablo González Casanova" de la Escuela Preparatoria (Prepa Tenancingo)',
    'Plantel "Ignacio Ramírez Calzada" de la Escuela Preparatoria (Prepa 4)',
    'Plantel "Lic. Adolfo López Mateos" de la Escuela Preparatoria (Prepa 1)',
    'Plantel "Nezahualcóyotl" de la Escuela Preparatoria (Prepa 2)',
    'Plantel "Sor Juana Inés de la Cruz" de la Escuela Preparatoria (Prepa Amecameca)',
    'Plantel "Texcoco" de la Escuela Preparatoria (Prepa Texcoco)',
    'PREPARATORIA ABIERTA',
    'Preparatoria Agustín García Conde',
    'Preparatoria Centro Universitario de San Felipe del Progreso, A.C.',
    'Preparatoria Colegio de la Comunidad de Ciudad Nezahualcóyotl, A.C.',
    'Preparatoria de la Unidad Pedagógica Aristos',
    'Preparatoria Dr. Jorge Jiménez Cantú',
    'Preparatoria Estado de CONAMAT',
    'Preparatoria Estado de México',
    'PREPARATORIA ETAC',
    'Preparatoria Federal por Cooperación-Melchor Ocampo-',
    'Preparatoria Federal por Cooperación-Prof. Pinito Reynoso Bejarano-',
    'Preparatoria Ignacio Manuel Altamirano',
    'PREPARATORIA N° 8 DE CD ALTAMIRANO GUERRERO MEXICO',
    'Preparatoria Regional de Santiago Tianguistenco',
    'Preparatoria Toluca, S.C.',
    'Servicios Educativos Integrados Al Edo Mex.',
    'SERVICIOS EDUCATIVOS SUPERIORES, S.C',
    'Sevicios educativos integrados al estado de mexico',
    'Sor Juana Ines de la Cruz-Centro de Bachillerato Tecnológico Unidad academica preparatoria # 41',
    'Unidad Cultural Israel, S.C.',
    'UNIVERSIDAD AUTÓNOMA DE GUERRERO (CONAMAT)',
    'UNIVERSIDAD DE IXTLAHUACA CUI',
    'UNIVERSIDAD DEL VALLE DE MEXICO',
    'Universidad del Valle de México-Campus Toluca-',
    'Universidad HUNAB',
    'Universidad Isidro Fabela de Toluca, S.C.',
    'Universidad Latina',
    'UNIVERSIDAD MEXICANA DE INNOVACIÓN DE NEGOCIOS',
    'UNIVERSIDAD POPULAR AUTONOMA DE VERACRUZ',
    'Universidad TecMilenio',
    'Universidad TecMilenio-Campus Toluca-',
    'Universidad Tecnológica de México',
    'UNIVERSIDAD TRES CULTURAS',
    'Universidad Vasco de Quiroga-Campus Ciudad Hidalgo-',
    'Otro',
  ],
];
